project:
  type: book

book:
  title: Tidyverse style guide
  author: The tidyverse team

  site-url: https://style.tidyverse.org
  repo-url: https://github.com/tidyverse/style/
  repo-branch: main
  repo-actions: [edit, issue]

  chapters:
  - index.qmd

  - part: Analyses
    chapters:
    - files.qmd
    - syntax.qmd
    - functions.qmd
    - pipes.qmd
    - ggplot2.qmd

  - part: Packages
    chapters:
    - package-files.qmd
    - documentation.qmd
    - tests.qmd
    - errors.qmd
    - news.qmd

  - part: Other
    chapters:
    - git.qmd

format:
  html:
    code-link: true
    include-in-header: "plausible.html"
    callout-appearance: simple

knitr:
  opts_chunk:
    eval: false
