on:
  push:
    branches: [main, master]
  pull_request:
  workflow_dispatch:

name: quarto.yml

jobs:
  quarto:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/install-quarto@v1

      - name: Render book
        run: quarto render

      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: _book
